---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-credentials
  namespace: platform-services
spec:
  encryptedData:
    password: AgAfkGz9Ggsoz0DjBZxeI9ehJlUhzebK76AZr7ojP22O7b6cohaEetYxyqvQOVzqlLETosggQ7KW5SROtXzj3d38k17YlZKA8SEBjgCSZO4ki/CFEbJund6jWVTcrTfILaizVNV1LV3FRhEMvErieStDx4t3QH/E0ouxLVfl5BLGALfWE+b3rYHtyR4FtqYnNkEBWGUClfjSPuU8LHM+zTwv8grGchXfn7Hja2/z6YhVs7yt4JDXtHm0d9Ry86kjEdRhpX6h9kzHc3SSNHuUYXMZoyv5PnO/hrUCeR8Oz4AOB75FhCLNU6j9BuMXS0cyro3UrMEFZVvU52Plq531IM+zAY8yqA7Xwg2v2z88sat/RA3A0gpTjPLoQOV9jP3BZGX3Sk6mWHo65HkIfMVpKoHhsd4QN/XF9A3SR4fP+PdijzVxRMRZKlKIR5BNMkhJdjHB6WNj5U7Yc60puDoAHpa1+XR14xU5cRYr1Boy20Vr5lX3pJyJ6aakxy3MN1/igv86jO4W+FK2QejUePi9zLmPCxxWRTVDZt3gO7XiMn1DPFr3g2fwYHk1T8cTwDWqQHuJtAy1CHZHJL9YEq/3caF+hG9VW8zwSlWrYgBjJrpKK0DpuR2VdJ12GMko18jdosPyV2P1ZV6sQ0ENVeSxQbWN4Y+fsFyVNIzMa87P4eaQG1bk9x2IcmPGO9uPWxlVt6KfQlzBtRe/pMyjd5x12wgV8ioeDrKWCsuDwrqDkJFbo/68LP0=
    username: AgALEESjGj50Nsou7upjDA5UbnBe5wkbUQmlT1HB+ZphqVsPH24izj0jgrhdLD54Hh9DSnNQhb96WBgDgM3nm5C1xafmuaYZiayJIix4BlXTZ6apbDtG40eRZ7G3PQY2seQj2H2W1dIEz8sk+j1bWx3ohODjCaZspPJcg99aqHKZKy3/+WkeGO/DSB33uaot7ZeHHTSn3z9x+w1JF/kbJzkh3Ra+20BpRe8GZRpFFu2mkBU1V29+bWHcvTlCBzooPjF8LI9FNgvCxsIlSWi6rdFlAT7wUPfSDMKGADp822ruf1a2VtiyjvNkm3JTpOJe/e48UL38L+9BXr3qX3u123H6LleDC/D0LG65m5hlu9/227WP2Ak1V3zD2kEVgXgX3l32GfzJVgK5z+1Fp5BG4o2KoYQ+pyZ80mpWIThLVqRSCAkcFNqHfuHFWApCFSRXhUa1t4rUWxoPiBXm9CdV/7iwsI3Bk8cSqgYb42FcoOzxbHReXlDzOKAsfysq6FuncFiUTAWHk6q79zvjKsSLL0O72tNtu0QEBBJZ5sJ/asZOVgms6ejv4RlZnr82v1XWneMzD5uXN3xEuSU559GNYvjPxt/mNkxuwLx92Yl7oFyLXXvGhk8AbYUSRz+ZY7UFIvqEeoemefFh85Iryh9sAlUhkCPXSMeuxDQJ43LhRCBNS/bEG57EwdGv0KPHClyn1H+oXuawwVM=
  template:
    metadata:
      creationTimestamp: null
      name: docker-credentials
      namespace: platform-services
