---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jwt-secret
  namespace: platform-services
spec:
  encryptedData:
    jwt-secret: AgAuivDCc51Ly9cHVB8WoCujiAMkds8GZiM6rhXoOU1vYW1iTNPDPnIP//qy1fAa8lDzj9FT2aheVVfWf4I0GG+ffl0JAqAOS+JJmGTVg2zPSwuJ5mXMg+3jkaSnu97n7lb8F48l4bBOdprVO6JScaFoDP998cWzpay/0tqoQdVjGIkh7thwZD6JCmL9Z3SCXSwT07uBpkRI6XW8Ze8EBwALR1SqgnujNyM3Bhi45XM7mAcVLZ3nYPZvVPh9aDDRqHBOBg3TcioMlaQOejspUtAYDHU9V/pQFGPjeNl8OGh4MoaQRsAhKwGSPX0f2mHc4ahP8PpgWypwmC5rPiw+KdhS9BR//UGHzi3fMJeWz3MQVlcZ39ZV+i1lVmx+z0ZpCXK4fI383VO/PZfghXVB0yGJsl6laKfhayfl2MqYx9nWBuKL2lAoTAY5QiKuL133uZ0pyehAU2ou89Gx8awl1r6/quHRLqNxwjGQRPf6XvS83T3C9HYJmHS+SVHwCxMUnFkmHW94fknfRt8O2ojI//GRFgiU2HrGKNu+rJG8iSyOc+oLyudB4OHH5DePJ/ZK4LBhTf6Va645Hf4cog5WmYQeiKh2+vnFeJtYNEAfTxWJdlRqc3zD5xisA1icwSjI7y4jF1m3/7FR0XrqUjUD08h/Hj23KDlaWA4Cwi27U6su6sIbYKuL0jlTMY1VwmcKhRMW6cwZI4f3lrQ/BQL9liAVHKy/BL1+uqS/2sXr0XzFuRKxfRPhijfHzJfJiR/xlNTeUgBfhSMkJzDGZpxSWGHhbK5h5VLtjOYVZUW3mbgSSCR1f14=
  template:
    metadata:
      creationTimestamp: null
      name: jwt-secret
      namespace: platform-services
