---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: platform-services
spec:
  encryptedData:
    postgres-password: AgC1jjMgq3lYVCRgfWRndoU5SNa4zji9G/3lxaS3XQngFna7r01/Yf+fC5atnZZf/Qesrgm/ZLAnWA+5RFv9gnsly2Na5xro7C0K6oA5F21XgNsdVB/fDHU6iovizDPew4d+KBWZg8sxiZI22I9cX4rLPW/4L9w0nl8wL9R0QnZI4sDxUpV6aPWlBngURlNhK1qL6rkDg9UW2DtBADxMAaFyZ7xwNKNV4wJUQ7fum7hH0TVZ5oX9f/P2X9qUvQ7dW4WAAwpswRJm25tHJ07Bpq3UZ2PSDBaPKuylsa8waj8O3aMy4aJSv0bExZmiov6/HgTo7l4WhJj3F8hE913j0UtOTdb1tIUW/okxDMwMUyb4JggVnOEM2hx8FbhnPPYRObMcSJ5/Q7pyVHR8Ki0mWGCtDw2tmi1P8WFaf80cDJ7iFUNaOmgzqZbXqDwL0AckBX75xzPKOO18OtTvG/M8gJBaAwEKZbUCMNn1WupW8cs7yxaLLB/vGepDO9Y4ZtmIiWM0MlMVr/2hpWZTqUrCHI6KRwaKsLpJtpnIfa3JXN4BRnPnoOJ9y/vDzKkCIH4ohqgdd07nZOale31jDZkR//GwRDYVy5KSBBs+4X/4CbzKyPEmS8LRez9W1Ud1i89qcq33cbgmiTyGunFXNFmZ7ryGdSgs4uPc8Kc0ZuE8hix6ZVU+3s/fm7F8HZJqCdPl0upQ+D5IUT9RY2U7d2fS0VP32S4iHg5Bpb///1dvDyR6qA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: platform-services
