apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storefront-wildcard
  namespace: platform-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: '*.fv-company.com'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storefront-renderer
            port:
              number: 80
  tls:
  - hosts:
    - '*.fv-company.com'
    secretName: wildcard-tls
